# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - davinci-teste

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'microsoft'

# Mude para o diretório onde o pom.xml está localizado
      - name: Build with Maven
        working-directory: 'Challenge_JavaV.3/insights'
        run: mvn clean install

# Verifique os arquivos gerados no diretório target
      - name: List files in target directory
        run: ls -la Challenge_JavaV.3/insights/target

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: java-app
          path: 'Challenge_JavaV.3/insights/target/*.jar'

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B3DE269519A04FF6AF6DC4FB019E106D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3FE57C2B7A7540B1ACAC029A25EA1223 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0F817667AFA24176B3C9AE50B5ABE087 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'davinci-teste'
          slot-name: 'Production'
          package: '*.jar'
          
